"""create_songs_table

Revision ID: e3d383bcb89c
Revises:
Create Date: 2025-06-24 17:00:05.710328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d383bcb89c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('singer', sa.String(), nullable=False),
    sa.Column('composer', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('youtube_link', sa.String(), nullable=True),
    sa.Column('spotify_link', sa.String(), nullable=True),
    sa.Column('apple_music_link', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('cover_art_url', sa.String(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
